dist: trusty
language: java
jdk: oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
    app: github-spring-petclinic
